#!/bin/sh

google_start='google.*##.g:has(a[href*="'
google_end='"])'

ddg_start='duckduckgo.*##.results > div:has(a[href*="'
ddg_end='"])'

if [ -f ./blocklist.txt ]; then
  truncate -s 0 ./blocklist.txt
else
  touch ./blocklist.txt
fi

printf '[Adblock]\n' >> ./blocklist.txt
printf '! Title: Spammy Sites Blocklist\n' >> ./blocklist.txt
printf '! Expires: 7 days (update frequency)\n' >> ./blocklist.txt
printf '! Version: 1\n' >> ./blocklist.txt
printf '! Last modified: %s\n' "$(date +'%d %B %Y')" >> ./blocklist.txt
printf '! Homepage: https://github.com/tomaskala/blocklists\n' >> ./blocklist.txt
printf '! Description: This filter removes spammy websites from search results\n' >> ./blocklist.txt
printf '!---------------------------------------------------------------------\n' >> ./blocklist.txt
printf '\n' >> ./blocklist.txt

for partial in ./src/*.txt; do
  if [ "$(basename "${partial}")" = verbatim.txt ]; then
    cat "${partial}" >> ./blocklist.txt
  else
    awk \
      -v google_start="${google_start}" \
      -v google_end="${google_end}" \
      -v ddg_start="${ddg_start}" \
      -v ddg_end="${ddg_end}" \
      '
      {
        print $0
        sub(/^\*:\/\//, "")  # Remove the leading *://
        sub(/^\*\./, "")     # Remove the leading *.
        sub(/\/\*$/, "")     # Remove the trailing /*
        print google_start $0 google_end
        print ddg_start $0 ddg_end
      }
      ' "${partial}" >> ./blocklist.txt
  fi
done
